# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Um título para noticia', max_length=100)),
                ('text', models.TextField(help_text='Inclua um texto simples, sem tags')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
            },
        ),
    ]
