# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161006_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
