# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161006_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(default='Sem título', max_length=100)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reference_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
